# Generated by Django 6.0.2 on 2026-06-08 14:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='claim',
            name='org',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='claims', to='App.org'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='item',
            name='status',
            field=models.CharField(choices=[('found', 'Found'), ('claimed', 'Claimed')], default='found', max_length=20),
        ),
    ]
