# Generated by Django 6.0.2 on 2026-06-09 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0002_claim_org_alter_item_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='org',
            name='owner_number',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
