# Generated by Django 6.0.2 on 2026-06-09 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0004_plan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='name',
            field=models.CharField(default='Name', max_length=50),
        ),
    ]
