# Generated by Django 6.0.2 on 2026-06-09 13:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0005_alter_plan_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='org',
            name='plan',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='organizations_plan', to='App.plan'),
        ),
    ]
