# Generated by Django 6.0.2 on 2026-06-14 17:14

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0006_org_plan'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='org',
            name='App_org_orgname_652931_idx',
        ),
        migrations.AddField(
            model_name='org',
            name='is_trial',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='org',
            name='subscription_end',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='org',
            name='trial_end',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='org',
            name='trial_start',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='org',
            name='date_joined',
            field=models.DateField(auto_now_add=True),
        ),
    ]
