# Generated by Django 6.0.2 on 2026-06-14 17:21

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0007_remove_org_app_org_orgname_652931_idx_org_is_trial_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='org',
            name='trial_start',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
